version: "3.8"
services:
  grafana:
    image: grafana/grafana
    networks: 
      network:
        aliases:
          - grafana

    ports: 
      - "3000:3000"

    volumes:
    - type: volume
      source: storage
      target: /var/lib/grafana
    - type: volume
      source: config
      target: /etc/grafana

    deploy:
      restart_policy:
        condition: on-failure
        
  prometheus:
    image: prom/prometheus
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention.time=30d'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
    networks: 
      network:
        aliases:
          - prometheus

    ports:
      - "9090:9090"

    volumes:
    - type: volume
      source: db-data
      target: /prometheus
    - ./prometheus.yml:/etc/prometheus/prometheus.yml

    deploy:
      restart_policy:
        condition: on-failure

  prometheus-exporter:
    image: prom/blackbox-exporter
    networks: 
      network:
        aliases:
          - prometheus-exporter      

    volumes:
      - ./prometheus-exporter.yml:/etc/blackbox_exporter/config.yml

    ports:
      - "9115:9115"

    deploy:
      restart_policy:
        condition: on-failure
      

networks:
  network:

volumes:
  db-data:
  storage:
  config:
