{
 "title": "Internet statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "probe_host",
    "label": "Probe Host (Internal)",
    "query": {
     "query": "label_values(probe_success, job)"
    }
   },
   {
    "name": "probe_target",
    "label": "Probe Target",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   },
   { "name": "metric_cutoff", "label": "Metric Cutoff", "query": "inf,4,3,2,1" },
   {
    "name": "phase_exclude",
    "label": "Excluded Phases",
    "query": "connect,processing,resolve,tls,transfer"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Duration - Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(sum(probe_http_duration_seconds{instance=~\"$probe_target\", job=~\"internet-performance@($probe_host)\", phase!~\"$phase_exclude\"}) without (phase) < $metric_cutoff, \"proxy\", \"$1\", \"job\", \"internet-performance@(.*)\")) by (proxy)",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  {
   "title": "Request Duration - $probe_target",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "repeat": "probe_target",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(probe_http_duration_seconds{instance=~\"$probe_target\", job=~\"internet-performance@($probe_host)\", phase!~\"$phase_exclude\"}) without (phase) < $metric_cutoff, \"proxy\", \"$1\", \"job\", \"internet-performance@(.*)\")",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  { "title": "Drilldown: $probe_host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 }, "repeat": "probe_host" },
  {
   "title": "Request Drilldown - $probe_target @ $probe_host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 128 },
   "repeat": "probe_target",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$probe_target\", job=\"internet-performance@$probe_host\", phase!~\"$phase_exclude\"} < $metric_cutoff",
     "legendFormat": "{{ phase}}"
    }
   ]
  }
 ]
}